name: CI/CD LeetCode Patterns

on:
  push:
    branches:
      - main # Trigger workflow on push to 'main'
  pull_request:
    branches:
      - main # Trigger workflow on pull requests targeting 'main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Use a Linux VM for perfomance

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Fetch the repository at the triggering commit
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with :
          dotnet-version: 8.0 # Use the .NET SDK version 8.0

      - name: Restore dependencies
        run: dotnet restore # Restore NuGet packages
      
      - name: Build
        run: dotnet build --configuration Release --no-restore # Build the solution
      
      - name: Test
        run: dotnet test --configuration Release --no-restore # Run your tests