name: CI/CD LeetCode Patterns

on:
  push:
    paths:
      - '**/*.cs'       # Include all C# source files
      - '**/*.csproj'   # Include project files
      - '**/*.sln'      # Include solution file
    branches:
      - main # Trigger workflow on push to 'main'
  pull_request:
    branches:
      - main # Trigger workflow on pull requests targeting 'main'
  workflow_dispatch:  # Allow workflow to be triggered Manually

jobs:
  build:
    runs-on: ubuntu-latest # Use a Linux VM for perfomance

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Fetch the repository at the triggering commit
      
          # Cache NuGet packages
      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages  # Path to the NuGet package cache
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}  # Cache key depends on .csproj file hashes
          restore-keys: |
            ${{ runner.os }}-nuget-
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with :
          dotnet-version: 8.0 # Use the .NET SDK version 8.0

      - name: Restore dependencies
        run: dotnet restore # Restore NuGet packages
      
      - name: Build
        run: dotnet build --configuration Release --no-restore # Build the solution
      
  test:
    needs: build  # Ensure the test job runs after the build job
    runs-on: ubuntu-latest  # Or windows-latest depending on your needs
    
    steps:
      - name: Test
        run: dotnet test --configuration Release --no-restore # Run your tests