name: CI/CD LeetCode Patterns

on:
  push:
    paths:
      - '**/*.cs'       # Include all C# source files
      - '**/*.csproj'   # Include project files
      - '**/*.sln'      # Include solution file
    branches:
      - main # Trigger workflow on push to 'main'
  pull_request:
    branches:
      - main # Trigger workflow on pull requests targeting 'main'
  workflow_dispatch:  # Allow workflow to be triggered Manually

jobs:
  build:
    runs-on: ubuntu-latest # Use a Linux VM for perfomance
    timeout-minutes: 30  # Set a timeout of 30 minutes for this job

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Fetch the repository at the triggering commit
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with :
          dotnet-version: 8.0 # Use the .NET SDK version 8.0

      # Cache NuGet packages
      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages  # Path to the NuGet package cache
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}  # Cache key depends on .csproj file hashes
          restore-keys: |
            ${{ runner.os }}-nuget-
          
      - name: Restore dependencies
        run: dotnet restore # Restore NuGet packages

      # Restore build cache (bin/obj)
      - name: Restore build cache
        uses: actions/cache@v4
        with:
          path: |
            **/bin
            **/obj
          key: ${{ runner.os }}-build-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Build
        run: dotnet build --configuration Release --no-restore # Build the solution

        # Cache build outputs (bin/obj)
      - name: Cache build outputs
        uses: actions/cache@v4
        with:
          path: |
            **/bin
            **/obj
          key: ${{ runner.os }}-build-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-build-
      
  test:
    needs: build  # Ensure the test job runs after the build job
    runs-on: ubuntu-latest  # Or windows-latest depending on your needs
    timeout-minutes: 30  # Set a timeout of 30 minutes for this job

    steps:
      # Runs unit tests in Release configuration without rebuilding or restoring dependencies
      - name: Test
        run: dotnet test ./LeetCodePatterns.Tests/LeetCodePatterns.Tests.csproj --configuration Release --no-build --no-restore